//! Evidence bundle writer and replay manifest consumer.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use thiserror::Error;
use tomorrowci_core::{
    redaction::redact_secrets, BreakageFrontier, CommandSpec, Config, EnvironmentSpec,
    ExecutionPlan, ExecutionResult, FailureSignature, RawExecutionResult, RepositorySnapshot,
    RunManifest, Scenario, ScenarioVerdict,
};

#[derive(Debug, Error)]
pub enum EvidenceError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("json: {0}")]
    Json(#[from] serde_json::Error),
    #[error("missing evidence: {0}")]
    Missing(String),
    #[error("{0}")]
    Other(String),
}

pub type Result<T> = std::result::Result<T, EvidenceError>;

pub struct EvidenceStore {
    pub root: PathBuf,
    pub run_id: String,
}

impl EvidenceStore {
    pub fn create(base: &Path, run_id: &str) -> Result<Self> {
        let root = base.join("runs").join(run_id);
        fs::create_dir_all(root.join("scenarios"))?;
        Ok(Self {
            root,
            run_id: run_id.to_string(),
        })
    }

    pub fn open(base: &Path, run_id: &str) -> Result<Self> {
        let root = base.join("runs").join(run_id);
        if !root.exists() {
            return Err(EvidenceError::Missing(format!(
                "run directory not found: {}",
                root.display()
            )));
        }
        Ok(Self {
            root,
            run_id: run_id.to_string(),
        })
    }

    pub fn write_json<T: Serialize + ?Sized>(&self, name: &str, value: &T) -> Result<PathBuf> {
        let path = self.root.join(name);
        let json = serde_json::to_string_pretty(value)?;
        fs::write(&path, json)?;
        Ok(path)
    }

    pub fn write_run_manifest(&self, manifest: &RunManifest) -> Result<()> {
        self.write_json("run.json", manifest)?;
        Ok(())
    }

    pub fn write_repository(&self, repo: &RepositorySnapshot) -> Result<()> {
        self.write_json("repository.json", repo)?;
        Ok(())
    }

    pub fn write_config(&self, config: &Config) -> Result<()> {
        self.write_json("config.normalized.json", config)?;
        Ok(())
    }

    pub fn write_plan(&self, plan: &ExecutionPlan) -> Result<()> {
        self.write_json("plan.json", plan)?;
        Ok(())
    }

    pub fn write_candidates(&self, candidates: &serde_json::Value) -> Result<()> {
        self.write_json("candidates.json", candidates)?;
        Ok(())
    }

    pub fn write_verdicts(&self, verdicts: &[ScenarioVerdict]) -> Result<()> {
        self.write_json("verdicts.json", verdicts)?;
        Ok(())
    }

    pub fn write_frontier(&self, frontier: &BreakageFrontier) -> Result<()> {
        self.write_json("frontier.json", frontier)?;
        Ok(())
    }

    pub fn scenario_dir(&self, scenario_id: &str) -> PathBuf {
        self.root.join("scenarios").join(scenario_id)
    }

    pub fn write_scenario_bundle(
        &self,
        scenario: &Scenario,
        env: &EnvironmentSpec,
        commands: &[CommandSpec],
        raw: &RawExecutionResult,
        result: &ExecutionResult,
        failure: Option<&FailureSignature>,
    ) -> Result<PathBuf> {
        let dir = self.scenario_dir(&scenario.id.0);
        fs::create_dir_all(&dir)?;

        write_json(&dir.join("scenario.json"), scenario)?;
        write_json(&dir.join("environment.json"), env)?;
        write_json(&dir.join("commands.json"), commands)?;

        let stdout = redact_secrets(&raw.stdout);
        let stderr = redact_secrets(&raw.stderr);
        // Cap log size (~2 MiB)
        let stdout = cap_bytes(&stdout, 2 * 1024 * 1024);
        let stderr = cap_bytes(&stderr, 2 * 1024 * 1024);
        fs::write(dir.join("stdout.log"), &stdout)?;
        fs::write(dir.join("stderr.log"), &stderr)?;
        write_json(&dir.join("result.json"), result)?;
        if let Some(f) = failure {
            write_json(&dir.join("failure-signature.json"), f)?;
        }

        let replay = ReplayManifest {
            run_id: self.run_id.clone(),
            scenario_id: scenario.id.0.clone(),
            image_ref: env.image_ref.clone(),
            image_digest: env.image_digest.clone(),
            commands: commands.to_vec(),
            workdir: env.workdir.clone(),
            memory_mb: env.memory_mb,
            cpus: env.cpus,
            pids_limit: env.pids_limit,
            timeout_seconds: env.timeout_seconds,
            network_mode: format!("{:?}", env.network_mode),
        };
        write_json(&dir.join("replay-manifest.json"), &replay)?;

        // Shell helpers that document exact recorded commands (consumer uses manifest)
        let mut sh = String::from("#!/usr/bin/env bash\nset -euo pipefail\n# Generated by TomorrowCI — uses recorded manifest, not a new plan\n");
        sh.push_str(&format!(
            "echo 'Replay scenario {} from run {}'\n",
            scenario.id, self.run_id
        ));
        sh.push_str("echo 'Use: tomorrowci replay <run-id> --scenario <scenario-id>'\n");
        for c in commands {
            sh.push_str(&format!(
                "# {} {}\n",
                c.program,
                c.args.join(" ")
            ));
        }
        fs::write(dir.join("replay.sh"), sh)?;

        let mut ps1 = String::from("# Generated by TomorrowCI\n");
        ps1.push_str(&format!(
            "Write-Host 'Replay scenario {} from run {}'\n",
            scenario.id, self.run_id
        ));
        ps1.push_str("Write-Host 'Use: tomorrowci replay <run-id> --scenario <scenario-id>'\n");
        fs::write(dir.join("replay.ps1"), ps1)?;

        write_checksums(&dir)?;
        Ok(dir)
    }

    pub fn load_replay_manifest(&self, scenario_id: &str) -> Result<ReplayManifest> {
        let path = self.scenario_dir(scenario_id).join("replay-manifest.json");
        if !path.exists() {
            return Err(EvidenceError::Missing(format!(
                "replay-manifest.json missing for scenario {scenario_id}"
            )));
        }
        let raw = fs::read_to_string(path)?;
        Ok(serde_json::from_str(&raw)?)
    }

    pub fn load_verdicts(&self) -> Result<Vec<ScenarioVerdict>> {
        let path = self.root.join("verdicts.json");
        let raw = fs::read_to_string(path)?;
        Ok(serde_json::from_str(&raw)?)
    }

    pub fn load_frontier(&self) -> Result<BreakageFrontier> {
        let path = self.root.join("frontier.json");
        let raw = fs::read_to_string(path)?;
        Ok(serde_json::from_str(&raw)?)
    }

    pub fn load_run(&self) -> Result<RunManifest> {
        let path = self.root.join("run.json");
        let raw = fs::read_to_string(path)?;
        Ok(serde_json::from_str(&raw)?)
    }

    pub fn finalize_checksums(&self) -> Result<()> {
        write_checksums(&self.root)?;
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReplayManifest {
    pub run_id: String,
    pub scenario_id: String,
    pub image_ref: String,
    pub image_digest: Option<String>,
    pub commands: Vec<CommandSpec>,
    pub workdir: String,
    pub memory_mb: u64,
    pub cpus: f64,
    pub pids_limit: u64,
    pub timeout_seconds: u64,
    pub network_mode: String,
}

fn write_json<T: Serialize + ?Sized>(path: &Path, value: &T) -> Result<()> {
    fs::write(path, serde_json::to_string_pretty(value)?)?;
    Ok(())
}

fn cap_bytes(s: &str, max: usize) -> String {
    if s.len() <= max {
        return s.to_string();
    }
    let half = max / 2;
    format!(
        "{}\n...[truncated {} bytes]...\n{}",
        &s[..half],
        s.len() - max,
        &s[s.len() - half..]
    )
}

fn write_checksums(dir: &Path) -> Result<()> {
    let mut lines = Vec::new();
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_file() && path.file_name().and_then(|n| n.to_str()) != Some("checksums.txt") {
            let data = fs::read(&path)?;
            let mut hasher = Sha256::new();
            hasher.update(&data);
            let digest = hex::encode(hasher.finalize());
            lines.push(format!(
                "{}  {}",
                digest,
                path.file_name().unwrap().to_string_lossy()
            ));
        }
    }
    lines.sort();
    let mut f = fs::File::create(dir.join("checksums.txt"))?;
    for line in lines {
        writeln!(f, "{line}")?;
    }
    Ok(())
}

pub fn sha256_file(path: &Path) -> Result<String> {
    let data = fs::read(path)?;
    let mut hasher = Sha256::new();
    hasher.update(&data);
    Ok(hex::encode(hasher.finalize()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;
    use tomorrowci_core::{DependencyMode, Ecosystem, EvidenceGrade, RunId, ScenarioKind};

    #[test]
    fn writes_and_loads_replay_manifest() {
        let d = tempdir().unwrap();
        let store = EvidenceStore::create(d.path(), "abc123").unwrap();
        let scenario = Scenario {
            id: tomorrowci_core::ScenarioId::new("s1"),
            kind: ScenarioKind::Baseline,
            ecosystem: Ecosystem::Python,
            label: "test".into(),
            runtime_version: "3.9".into(),
            dependency_mode: DependencyMode::Locked,
            image_ref: "python:3.9".into(),
            axes_changed: vec![],
            evidence_grade: EvidenceGrade::Observed,
            is_baseline: true,
            selection_reason: "t".into(),
        };
        let env = EnvironmentSpec {
            image_ref: "python:3.9".into(),
            image_digest: Some("sha256:deadbeef".into()),
            workdir: "/workspace".into(),
            user: None,
            env: Default::default(),
            mounts: vec![],
            network_mode: tomorrowci_core::NetworkMode::None,
            read_only_root: false,
            memory_mb: 1024,
            cpus: 1.0,
            pids_limit: 128,
            timeout_seconds: 60,
        };
        let raw = RawExecutionResult {
            exit_code: Some(0),
            signal: None,
            stdout: "ok".into(),
            stderr: String::new(),
            duration_ms: 1,
            timed_out: false,
            network_used: false,
            error: None,
        };
        let result = ExecutionResult {
            scenario_id: scenario.id.clone(),
            attempt: 1,
            exit_code: Some(0),
            signal: None,
            duration_ms: 1,
            timed_out: false,
            network_used: false,
            stdout_path: None,
            stderr_path: None,
            stdout_preview: "ok".into(),
            stderr_preview: String::new(),
            blocked_reason: None,
            image_ref: env.image_ref.clone(),
            image_digest: env.image_digest.clone(),
            commands: vec![],
        };
        store
            .write_scenario_bundle(&scenario, &env, &[], &raw, &result, None)
            .unwrap();
        let m = store.load_replay_manifest("s1").unwrap();
        assert_eq!(m.image_digest.as_deref(), Some("sha256:deadbeef"));
        assert_eq!(m.scenario_id, "s1");
        let _ = RunId::new();
    }
}
