#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 3 ]; then
  echo "usage: live-backtest.sh <tomorrowci-bin> <repository-root> <scratch-root>" >&2
  exit 2
fi

TOOL=$(realpath -e -- "$1")
SOURCE_ROOT=$(realpath -e -- "$2")
SCRATCH_ROOT=$3
SNAPSHOTS="$SOURCE_ROOT/fixtures/backtest-snapshots"

if python3 -c 'import json' >/dev/null 2>&1; then
  PYTHON_BIN=python3
elif python -c 'import json' >/dev/null 2>&1; then
  PYTHON_BIN=python
else
  echo "python3 or python is required to validate the backtest report" >&2
  exit 2
fi

if [ -e "$SCRATCH_ROOT" ]; then
  echo "scratch root must not already exist: $SCRATCH_ROOT" >&2
  exit 2
fi
mkdir -p -- "$SCRATCH_ROOT"

commit_fixture() {
  local repository=$1
  git -C "$repository" init --quiet
  git -C "$repository" config user.name tomorrowci-backtest
  git -C "$repository" config user.email tomorrowci-backtest@example.invalid
  git -C "$repository" add .
  GIT_AUTHOR_DATE=2026-01-15T14:00:00Z \
    GIT_COMMITTER_DATE=2026-01-15T14:00:00Z \
    git -C "$repository" commit --quiet -m snapshot-fixture
}

write_config() {
  local destination=$1
  local ecosystem=$2
  local runtime=$3
  local test_command=$4
  cat >"$destination" <<EOF
version: 1
project:
  ecosystem: $ecosystem
  test_command: $test_command
baseline:
  runtime: "$runtime"
  dependencies: locked
candidates:
  runtime:
    channels: [stable]
    max_versions: 1
  dependencies:
    latest_allowed: false
    prerelease: false
execution:
  max_scenarios: 1
  timeout_seconds: 600
  reruns_on_failure: 2
  max_parallel: 1
sandbox:
  engine: docker
  network: fetch-only
  memory_mb: 2048
  cpus: 2
  pids_limit: 256
EOF
}

PYTHON_REPO="$SCRATCH_ROOT/source-python"
mkdir -p -- "$PYTHON_REPO"
cat >"$PYTHON_REPO/requirements.txt" <<'REQ'
tomorrowci-snapshot-dep==1.0.0
REQ
cat >"$PYTHON_REPO/test_snapshot.py" <<'PY'
import unittest
import tomorrowci_snapshot_dep


class SnapshotTest(unittest.TestCase):
    def test_offline_source(self):
        marker = tomorrowci_snapshot_dep.snapshot_value()
        self.assertEqual(marker, "python-snapshot-dependency-1.0.0")
        print(marker)


if __name__ == "__main__":
    unittest.main()
PY
write_config "$PYTHON_REPO/.tomorrowci.yml" python 3.11 "python -m unittest discover -v"
commit_fixture "$PYTHON_REPO"

NODE_REPO="$SCRATCH_ROOT/source-node"
mkdir -p -- "$NODE_REPO"
cat >"$NODE_REPO/package.json" <<'JSON'
{
  "name": "tomorrowci-backtest-node",
  "version": "1.0.0",
  "private": true,
  "scripts": {"test": "node test.js"},
  "dependencies": {
    "tomorrowci-snapshot-dep": "file:.tomorrowci-backtest/registry-snapshot/payload/tomorrowci-snapshot-dep-1.0.0.tgz"
  }
}
JSON
cat >"$NODE_REPO/package-lock.json" <<'JSON'
{
  "name": "tomorrowci-backtest-node",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "tomorrowci-backtest-node",
      "version": "1.0.0",
      "dependencies": {
        "tomorrowci-snapshot-dep": "file:.tomorrowci-backtest/registry-snapshot/payload/tomorrowci-snapshot-dep-1.0.0.tgz"
      }
    },
    "node_modules/tomorrowci-snapshot-dep": {
      "version": "1.0.0",
      "resolved": "file:.tomorrowci-backtest/registry-snapshot/payload/tomorrowci-snapshot-dep-1.0.0.tgz",
      "integrity": "sha512-OauggzxOJUSDuvcLUcY0rRwOLiRB48GGFqI/X3xujKobM90vSolCkQQZI7XBX8mWCQI2YZWDqflonrI5M/1vDQ=="
    }
  }
}
JSON
cat >"$NODE_REPO/test.js" <<'JS'
'use strict';
const assert = require('node:assert/strict');
const dependency = require('tomorrowci-snapshot-dep');
const marker = dependency.snapshotValue();
assert.equal(marker, 'node-snapshot-dependency-1.0.0');
console.log(marker);
JS
write_config "$NODE_REPO/.tomorrowci.yml" node 20 "npm test"
commit_fixture "$NODE_REPO"

RUST_REPO="$SCRATCH_ROOT/source-rust"
mkdir -p -- "$RUST_REPO/src"
cat >"$RUST_REPO/Cargo.toml" <<'TOML'
[package]
name = "tomorrowci-backtest-rust"
version = "1.0.0"
edition = "2021"

[workspace]

[dependencies]
tomorrowci-snapshot-dep = "=1.0.0"
TOML
cat >"$RUST_REPO/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "tomorrowci-backtest-rust"
version = "1.0.0"
dependencies = [
 "tomorrowci-snapshot-dep",
]

[[package]]
name = "tomorrowci-snapshot-dep"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
LOCK
cat >"$RUST_REPO/src/lib.rs" <<'RS'
pub fn answer() -> usize {
    42
}

#[cfg(test)]
mod tests {
    #[test]
    fn offline_source() {
        let marker = tomorrowci_snapshot_dep::snapshot_value();
        assert_eq!(marker, "rust-snapshot-dependency-1.0.0");
        println!("{marker}");
        assert_eq!(super::answer(), 42);
    }
}
RS
write_config "$RUST_REPO/.tomorrowci.yml" rust 1.85 "cargo test -- --nocapture"
commit_fixture "$RUST_REPO"

for ecosystem in python node rust; do
  repository="$SCRATCH_ROOT/source-$ecosystem"
  evidence="$SCRATCH_ROOT/evidence-$ecosystem"
  work="$SCRATCH_ROOT/work-$ecosystem"
  report="$SCRATCH_ROOT/backtest-$ecosystem.json"
  "$TOOL" \
    --evidence-root "$evidence" \
    --work-root "$work" \
    backtest "$repository" \
    --at 2026-01-15 \
    --until 2026-01-15 \
    --max-commits 1 \
    --max-scenarios 1 \
    --snapshot-registry "$SNAPSHOTS" \
    --out "$report"
  "$PYTHON_BIN" - "$report" <<'PY'
import json
import re
import sys

with open(sys.argv[1], encoding="utf-8") as report_file:
    report = json.load(report_file)
points = report.get("points", [])
assert len(points) == 1
point = points[0]
assert point.get("status") == "OK"
assert isinstance(point.get("run_id"), str) and point["run_id"]
proof = point.get("proof", {})
assert proof.get("proof_sha256", "").startswith("sha256:")
assert re.fullmatch(r"[0-9a-f]{64}", proof.get("sealed_inventory_sha256", ""))
PY
  shopt -s nullglob
  proofs=("$evidence"/backtests/*)
  test "${#proofs[@]}" -eq 1
  "$TOOL" backtest-verify "${proofs[0]}"
  case "$ecosystem" in
    python) marker="python-snapshot-dependency-1.0.0" ;;
    node) marker="node-snapshot-dependency-1.0.0" ;;
    rust) marker="rust-snapshot-dependency-1.0.0" ;;
  esac
  grep -R -F -- "$marker" "${proofs[0]}/witness/run/scenarios" >/dev/null
done

echo "live historical backtest PASS (python,node,rust; pinned dependencies installed offline; sealed run/snapshot witnesses; repository bytes excluded)"
