//! Self-contained backtest timeline HTML (real BacktestReport JSON).

use crate::Result;
use std::path::Path;
use tomorrowci_core::backtest::BacktestReport;
use tomorrowci_core::safety::escape_html;

pub fn write_backtest_html(path: &Path, report: &BacktestReport) -> Result<()> {
    let mut rows = String::new();
    for p in &report.points {
        let sha = if p.commit_sha.len() >= 8 {
            &p.commit_sha[..8]
        } else {
            p.commit_sha.as_str()
        };
        let horizon = p
            .horizon_label
            .as_deref()
            .map(escape_html)
            .unwrap_or_else(|| "(none)".into());
        let status = format!("{:?}", p.status);
        let when = p
            .committed_at
            .map(|t| t.to_rfc3339())
            .unwrap_or_else(|| "—".into());
        let run = p.run_id.as_deref().unwrap_or("—");
        rows.push_str(&format!(
            "<tr><td><code>{sha}</code></td><td>{when}</td><td><span class=\"badge\">{status}</span></td>\
             <td>{horizon}</td><td><code>{run}</code></td><td class=\"muted\">{detail}</td></tr>",
            sha = escape_html(sha),
            when = escape_html(&when),
            status = escape_html(&status),
            horizon = horizon,
            run = escape_html(run),
            detail = escape_html(&p.detail.chars().take(120).collect::<String>()),
        ));
    }

    let html = format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>TomorrowCI Backtest Timeline</title>
<style>
:root {{ --bg:#0b1220; --panel:#121a2b; --text:#e8eefc; --muted:#9db0d0; --border:#243049; --accent:#63b3ed; }}
body {{ margin:0; font-family:system-ui,sans-serif; background:var(--bg); color:var(--text); line-height:1.5; }}
main {{ max-width:1100px; margin:0 auto; padding:1.25rem; }}
.panel {{ background:var(--panel); border:1px solid var(--border); border-radius:12px; padding:1rem; margin:1rem 0; }}
table {{ width:100%; border-collapse:collapse; }}
th,td {{ text-align:left; padding:.55rem .4rem; border-bottom:1px solid var(--border); vertical-align:top; }}
.muted {{ color:var(--muted); }}
.badge {{ border:1px solid var(--border); border-radius:999px; padding:.1rem .5rem; font-size:.75rem; }}
code {{ font-family:ui-monospace,monospace; }}
</style>
</head>
<body>
<main>
  <h1>Backtest timeline</h1>
  <p class="muted">{note}</p>
  <div class="panel">
    <p>Range: <strong>{at}</strong> → <strong>{until}</strong> · max_commits={max_c} · max_scenarios/point={max_s}</p>
    <p>Target: <code>{target}</code></p>
  </div>
  <div class="panel">
    <table>
      <caption class="muted">Commit sample points (oldest first)</caption>
      <thead>
        <tr><th>Commit</th><th>Committed</th><th>Status</th><th>Horizon</th><th>Run</th><th>Detail</th></tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
  </div>
  <p class="muted">Generated by TomorrowCI. Historical package indexes are NOT reconstructed in v0.1.</p>
</main>
</body>
</html>
"##,
        note = escape_html(&report.note),
        at = report.request.at,
        until = report.request.until,
        max_c = report.request.max_commits,
        max_s = report.request.max_scenarios_per_point,
        target = escape_html(&report.request.target),
    );
    super::atomic_write(path, html.as_bytes())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::NaiveDate;
    use std::fs;
    use tempfile::tempdir;
    use tomorrowci_core::backtest::{BacktestPoint, BacktestPointStatus, BacktestRequest};

    #[test]
    fn writes_html() {
        let d = tempdir().unwrap();
        let report = BacktestReport {
            request: BacktestRequest {
                target: ".".into(),
                at: NaiveDate::from_ymd_opt(2026, 1, 1).unwrap(),
                until: NaiveDate::from_ymd_opt(2026, 8, 1).unwrap(),
                max_commits: 2,
                max_scenarios_per_point: 3,
            },
            points: vec![BacktestPoint {
                commit_sha: "abc12345deadbeef".into(),
                committed_at: None,
                run_id: Some("run1".into()),
                frontier_observed: true,
                horizon_label: Some("Python 3.10".into()),
                status: BacktestPointStatus::Ok,
                detail: "ok".into(),
            }],
            note: "test".into(),
        };
        let path = d.path().join("bt.html");
        write_backtest_html(&path, &report).unwrap();
        let html = fs::read_to_string(path).unwrap();
        assert!(html.contains("abc12345"));
        assert!(html.contains("Python 3.10"));
    }
}
